color_schemes:
  stellarized_light: &stellarized_light
    primary:
      background: '#fceee0'
      foreground: '#4a5067'

    normal:
      black:   '#000000'
      red:     '#c6394c'
      green:   '#007f25'
      yellow:  '#8b6800'
      blue:    '#006dcc'
      magenta: '#c6394c'
      cyan:    '#0082ff'
      white:   '#f0f1ce'

    bright:
      black:   '#000000'
      red:     '#c6394c'
      green:   '#007f25'
      yellow:  '#8b6800'
      blue:    '#006dcc'
      magenta: '#c6394c'
      cyan:    '#0082ff'
      white:   '#f0f1ce'

  stellarized_dark: &stellarized_dark
    primary:
      background: '#222532'
      foreground: '#bead9d'

    normal:
      black:   '#000000'
      red:     '#c6394c'
      green:   '#007f25'
      yellow:  '#8b6800'
      blue:    '#006dcc'
      magenta: '#c6394c'
      cyan:    '#0082ff'
      white:   '#f0f1ce'

    bright:
      black:   '#000000'
      red:     '#c6394c'
      green:   '#007f25'
      yellow:  '#8b6800'
      blue:    '#006dcc'
      magenta: '#c6394c'
      cyan:    '#0082ff'
      white:   '#f0f1ce'

colors: *stellarized_dark
